language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env: COMPILER=g++-7
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - gcc-7
            - g++-7
      before_install: 
        - sudo apt-get -qq update
        - sudo apt-get -qq install -y libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
        - wget -O vulkansdk-linux-x86_64-1.1.106.0.run https://vulkan.lunarg.com/sdk/download/1.1.106.0/linux/vulkansdk-linux-x86_64-1.1.106.0.run
        - chmod ugo+x vulkansdk-linux-x86_64-1.1.106.0.run
        - ./vulkansdk-linux-x86_64-1.1.106.0.run
        - export VULKAN_SDK=$TRAVIS_BUILD_DIR/VulkanSDK/1.1.106.0/x86_64
      install: if [[ "$COMPILER" == "g++-7" ]]; then export CXX="g++-7" CC="gcc-7"; fi
      script:
        - libs/premake5/linux/premake5 gmake2
        - make
    - os: osx
      before_install:
        - wget -O vulkansdk-macos-1.1.106.0.tar.gz https://sdk.lunarg.com/sdk/download/1.1.106.0/mac/vulkansdk-macos-1.1.106.0.tar.gz?Human=true
        - tar -xzf vulkansdk-macos-1.1.106.0.tar.gz
        - export VULKAN_SDK=$TRAVIS_BUILD_DIR/vulkansdk-macos-1.1.106.0/macOS
      script:
        - libs/premake5/osx/premake5 gmake2
        - make
    - os: windows
      before_install:
        - curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.106.0/windows/VulkanSDK-1.1.106.0-Installer.exe
        - .\VulkanSDK.exe /S
      env: 
        - LABEL="windows-msvc" 
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
        - VULKAN_SDK="/C/VulkanSDK/1.1.106.0"
      script:
        - libs/premake5/windows/premake5.exe vs2017 
        - export PATH=$MSBUILD_PATH:$PATH 
        - MSBuild.exe TRAP.sln //t:Build