#ifndef _TRAP_GAMEPADCODES_H_
#define _TRAP_GAMEPADCODES_H_

#define TP_GAMEPAD_BUTTON_A 0
#define TP_GAMEPAD_BUTTON_B 1
#define TP_GAMEPAD_BUTTON_X 2
#define TP_GAMEPAD_BUTTON_Y 3
#define TP_GAMEPAD_BUTTON_LEFT_BUMPER 4
#define TP_GAMEPAD_BUTTON_RIGHT_BUMPER 5
#define TP_GAMEPAD_BUTTON_BACK 6
#define TP_GAMEPAD_BUTTON_START 7
#define TP_GAMEPAD_BUTTON_GUIDE 8
#define TP_GAMEPAD_BUTTON_LEFT_THUMB 9
#define TP_GAMEPAD_BUTTON_RIGHT_THUMB 10
#define TP_GAMEPAD_BUTTON_DPAD_UP 11
#define TP_GAMEPAD_BUTTON_DPAD_RIGHT 12
#define TP_GAMEPAD_BUTTON_DPAD_DOWN 13
#define TP_GAMEPAD_BUTTON_DPAD_LEFT 14
#define TP_GAMEPAD_BUTTON_CROSS TP_GAMEPAD_BUTTON_A
#define TP_GAMEPAD_BUTTON_CIRCLE TP_GAMEPAD_BUTTON_B
#define TP_GAMEPAD_BUTTON_SQUARE TP_GAMEPAD_BUTTON_X
#define TP_GAMEPAD_BUTTON_TRIANGLE TP_GAMEPAD_BUTTON_Y

#endif /*_TRAP_GAMEPADCODES_H_*/