version: '3'
services:
  worker:
    restart: unless-stopped
    image: trappedgames/github-actions-runner-windows:latest
    environment:
      GH_OWNER: GamesTrap
      GH_REPOSITORY: TRAP
      GH_TOKEN: <PAT_TOKEN>
      RUNNER_NAME: windows-v4-cpu
      RUNNER_LABELS: windows,x64,server,2022,cpu
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8G"
