version: '3'
services:
  worker:
    restart: unless-stopped
    image: trappedgames/gitea-actions-runner-linux:latest
    environment:
      GITEA_HOST: <GITEA_HOST_URL>
      RUNNER_NAME_PREFIX: ubuntu-v4-cpu
      RANDOM_RUNNER_SUFFIX: true
      RUNNER_TOKEN: <RUNNER_REGISTER_TOKEN>
      LABELS: linux,x64,ubuntu,"24.10",cpu
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8G"
