# Main Build CI. This compiles TRAP™ for Windows and Linux (Ubuntu)

name: Build-CI

# Controls when the workflow will run
on:
  # Run on all pull requests
  pull_request:
  # Run on main, master and dev branches
  push:
    branches: [ main, master, dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux-gcc-16:
    name: Build Linux GCC 16
    runs-on: [self-hosted, Linux, X64, ubuntu, "26.04", cpu]
    env:
      CC: gcc-16
      CXX: g++-16
    steps:
    - name: Cleanup workspace
      if: ${{ always() }}
      uses: gamestrap/gha-workspace-cleanup@a4ba9185d186048c239232b7164d5215aa544974 #v2.0.0
    - name: Checkout repository and submodules
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - name: Checkout submodules (with retries)
      run: |
        git submodule sync && \
        (git -c protocol.version=2 submodule update --init --force --depth=1 || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) \
        )
    - name: Checkout DiscordGameSDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_DISCORDGAMESDK
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_DISCORDGAMESDK: ${{ secrets.GIT_NDA_DEPS_DISCORDGAMESDK }}
      run: |
        cd Dependencies/DiscordGameSDK
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_DISCORDGAMESDK }}
        git pull origin main --depth 1
        cd ../..
    - name: Checkout NVIDIA Nsight Aftermath SDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_NSIGHTAFTERMATH
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_NSIGHTAFTERMATH: ${{ secrets.GIT_NDA_DEPS_NSIGHTAFTERMATH }}
      run: |
        cd Dependencies/Nsight-Aftermath
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_NSIGHTAFTERMATH }}
        git pull origin main --depth 1
        cd ../..
    - name: Checkout Steamworks SDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_STEAMWORKSSDK
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_STEAMWORKSSDK: ${{ secrets.GIT_NDA_DEPS_STEAMWORKSSDK }}
      run: |
        cd Dependencies/SteamworksSDK
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_STEAMWORKSSDK }}
        git pull origin main --depth 1
        cd ../..
    - name: Add toolchain ppa
      run: sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
    - name: Update package list
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install -y g++-16 mold xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols ninja-build
    - name: Make python3 available as python
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - name: Make pip3 available as pip
      run: sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
    - name: Make g++-16 available as g++
      run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-16 10
    - name: Make gcc-16 available as gcc
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-16 10
    - name: Make scripts and premake executable
      run: |
       chmod +x libs/premake5/linux/premake5
       chmod +x GeneratorScripts/GenerateProjectNinjaGCC.sh
    - name: Generate Ninja files
      run: |
       cd GeneratorScripts/
       ./GenerateProjectNinjaGCC.sh
       cd ..
    - name: Setup problem matchers
      uses: ./.github/composite/problem-matchers
    - name: Compile code
      run: ninja Release -j $(nproc)
    - name: Finalize data for artifact
      run: |
        cp -r Games/Headless-Tests/Assets bin/Release-linux-x86_64/Games/Headless-Tests/
        cp -r Games/Sandbox/Assets bin/Release-linux-x86_64/Games/Sandbox/
        cp -r Games/Tests/Assets bin/Release-linux-x86_64/Games/Tests/
        cp -r Games/Tests3D/Assets bin/Release-linux-x86_64/Games/Tests3D/
        cp -r Games/TRAP-Editor/Assets bin/Release-linux-x86_64/Games/TRAP-Editor/
        cp -r Games/TRAP-Editor/Resources bin/Release-linux-x86_64/Games/TRAP-Editor/
        cp -r Utility/QOIConv bin/Release-linux-x86_64/Utility/
        cp -r Licenses bin/Release-linux-x86_64/Licenses
        rm bin/Release-linux-x86_64/Utility/QOIConv/QOIConv.exe
    - name: Upload artifacts (TrappedGames)
      env:
        artifact_hostname: ${{secrets.ARTIFACT_HOST}}
      if: env.artifact_hostname != null
      uses: ./.github/composite/artifact-upload
      with:
        target-filename: Linux GCC Release Executables
        server-hostname: ${{ secrets.ARTIFACT_HOST }}
        server-share: "artifacts"
        server-username: ${{ secrets.ARTIFACT_USERNAME }}
        server-password: ${{ secrets.ARTIFACT_PASSWORD }}
        folder-to-upload: >
          bin/Release-linux-x86_64/./Games
          bin/Release-linux-x86_64/./Utility
          bin/Release-linux-x86_64/./UnitTests
          bin/Release-linux-x86_64/./Licenses
    - name: Upload artifacts (GitHub)
      env:
        artifact_hostname: ${{secrets.ARTIFACT_HOST}}
      if: env.artifact_hostname == null
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: Linux GCC Release Executables
        path: |
          bin/Release-linux-x86_64/Games
          bin/Release-linux-x86_64/Utility
          bin/Release-linux-x86_64/UnitTests
          bin/Release-linux-x86_64/Licenses
  build-linux-clang-22:
    name: Build Linux Clang 22
    runs-on: [self-hosted, Linux, X64, ubuntu, "26.04", cpu]
    env:
      CC: clang-22
      CXX: clang++-22
    steps:
    - name: Cleanup workspace
      if: ${{ always() }}
      uses: gamestrap/gha-workspace-cleanup@a4ba9185d186048c239232b7164d5215aa544974 #v2.0.0
    - name: Checkout repository and submodules
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - name: Checkout submodules (with retries)
      run: |
        git submodule sync && \
        (git -c protocol.version=2 submodule update --init --force --depth=1 || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) \
        )
    - name: Checkout DiscordGameSDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_DISCORDGAMESDK
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_DISCORDGAMESDK: ${{ secrets.GIT_NDA_DEPS_DISCORDGAMESDK }}
      run: |
        cd Dependencies/DiscordGameSDK
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_DISCORDGAMESDK }}
        git pull origin main --depth 1
        cd ../..
    - name: Checkout NVIDIA Nsight Aftermath SDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_NSIGHTAFTERMATH
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_NSIGHTAFTERMATH: ${{ secrets.GIT_NDA_DEPS_NSIGHTAFTERMATH }}
      run: |
        cd Dependencies/Nsight-Aftermath
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_NSIGHTAFTERMATH }}
        git pull origin main --depth 1
        cd ../..
    - name: Checkout Steamworks SDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_STEAMWORKSSDK
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_STEAMWORKSSDK: ${{ secrets.GIT_NDA_DEPS_STEAMWORKSSDK }}
      run: |
        cd Dependencies/SteamworksSDK
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_STEAMWORKSSDK }}
        git pull origin main --depth 1
        cd ../..
    - name: Add toolchain ppa
      run: sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
    - name: Update package list
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install -y clang-22 llvm-22 mold xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols ninja-build
    - name: Make python3 available as python
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - name: Make pip3 available as pip
      run: sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
    - name: Make llvm-ar-22 available as llvm-ar
      run: sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-22 10
    - name: Make clang-22 available as clang
      run: sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-22 10
    - name: Make clang++-22 available as clang++
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-22 10
    - name: Make scripts and premake executable
      run: |
        chmod +x libs/premake5/linux/premake5
        chmod +x GeneratorScripts/GenerateProjectNinjaClang.sh
    - name: Generate Ninja files
      run: |
        cd GeneratorScripts/
        ./GenerateProjectNinjaClang.sh
        cd ..
    - name: Setup problem matchers
      uses: ./.github/composite/problem-matchers
    - name: Compile code
      run: ninja Release -j $(nproc)
    - name: Finalize data for artifact
      run: |
        cp -r Games/Headless-Tests/Assets bin/Release-linux-x86_64/Games/Headless-Tests/
        cp -r Games/Sandbox/Assets bin/Release-linux-x86_64/Games/Sandbox/
        cp -r Games/Tests/Assets bin/Release-linux-x86_64/Games/Tests/
        cp -r Games/Tests3D/Assets bin/Release-linux-x86_64/Games/Tests3D/
        cp -r Games/TRAP-Editor/Assets bin/Release-linux-x86_64/Games/TRAP-Editor/
        cp -r Games/TRAP-Editor/Resources bin/Release-linux-x86_64/Games/TRAP-Editor/
        cp -r Utility/QOIConv bin/Release-linux-x86_64/Utility/
        cp -r Licenses bin/Release-linux-x86_64/Licenses
        rm bin/Release-linux-x86_64/Utility/QOIConv/QOIConv.exe
    - name: Upload artifacts (TrappedGames)
      env:
        artifact_hostname: ${{secrets.ARTIFACT_HOST}}
      if: env.artifact_hostname != null
      uses: ./.github/composite/artifact-upload
      with:
        target-filename: Linux Clang Release Executables
        server-hostname: ${{ secrets.ARTIFACT_HOST }}
        server-share: "artifacts"
        server-username: ${{ secrets.ARTIFACT_USERNAME }}
        server-password: ${{ secrets.ARTIFACT_PASSWORD }}
        folder-to-upload: >
          bin/Release-linux-x86_64/./Games
          bin/Release-linux-x86_64/./Utility
          bin/Release-linux-x86_64/./UnitTests
          bin/Release-linux-x86_64/./Licenses
    - name: Upload artifacts (GitHub)
      env:
        artifact_hostname: ${{secrets.ARTIFACT_HOST}}
      if: env.artifact_hostname == null
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: Linux Clang Release Executables
        path: |
          bin/Release-linux-x86_64/Games
          bin/Release-linux-x86_64/Utility
          bin/Release-linux-x86_64/UnitTests
          bin/Release-linux-x86_64/Licenses
  build-windows-msvc-2025:
    name: Build Windows MSVC 2025
    runs-on: [self-hosted, windows, "2025", X64, cpu]
    steps:
    - name: Cleanup workspace
      if: ${{ always() }}
      uses: gamestrap/gha-workspace-cleanup@a4ba9185d186048c239232b7164d5215aa544974 #v2.0.0
    - name: Checkout repository and submodules
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - name: Checkout submodules (with retries)
      shell: bash
      run: |
        git submodule sync && \
        (git -c protocol.version=2 submodule update --init --force --depth=1 || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) \
        )
    - name: Checkout DiscordGameSDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_DISCORDGAMESDK
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_DISCORDGAMESDK: ${{ secrets.GIT_NDA_DEPS_DISCORDGAMESDK }}
      run: |
        cd Dependencies/DiscordGameSDK
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_DISCORDGAMESDK }}
        git pull origin main --depth 1
        cd ../..
    - name: Checkout NVIDIA Nsight Aftermath SDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_NSIGHTAFTERMATH
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_NSIGHTAFTERMATH: ${{ secrets.GIT_NDA_DEPS_NSIGHTAFTERMATH }}
      run: |
        cd Dependencies/Nsight-Aftermath
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_NSIGHTAFTERMATH }}
        git pull origin main --depth 1
        cd ../..
    - name: Checkout Steamworks SDK
      if: env.HAS_GIT_NDA_DEPS && env.HAS_GIT_NDA_DEPS_STEAMWORKSSDK
      env:
        HAS_GIT_NDA_DEPS: ${{ secrets.GIT_NDA_DEPS }}
        HAS_GIT_NDA_DEPS_STEAMWORKSSDK: ${{ secrets.GIT_NDA_DEPS_STEAMWORKSSDK }}
      run: |
        cd Dependencies/SteamworksSDK
        git init
        git remote add origin ${{ secrets.GIT_NDA_DEPS }}/${{ secrets.GIT_NDA_DEPS_STEAMWORKSSDK }}
        git pull origin main --depth 1
        cd ../..
    - name: Setup developer console
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 #v1.13.0
      with:
        arch: x64
    - name: Generate Visual Studio 2026 Project files
      run: |
        cd GeneratorScripts
        .\GenerateProjectNinjaMSVC.bat
        cd ..
    - name: Setup problem matchers
      uses: ./.github/composite/problem-matchers
    - name: Compile code
      run: |
        $maxCPUCount = if($env:CONTAINER_MAX_CPUS) {$env:CONTAINER_MAX_CPUS} Else {$env:NUMBER_OF_PROCESSORS}
        ninja Release -j $maxCPUCount
    - name: Finalize data for artifact
      run: |
        Xcopy Games\Headless-Tests\Assets bin\Release-windows-x86_64\Games\Headless-Tests\Assets /I /H /E /C
        Xcopy Games\Sandbox\Assets bin\Release-windows-x86_64\Games\Sandbox\Assets /I /H /E /C
        Xcopy Games\Tests\Assets bin\Release-windows-x86_64\Games\Tests\Assets /I /H /E /C
        Xcopy Games\Tests3D\Assets bin\Release-windows-x86_64\Games\Tests3D\Assets /I /H /E /C
        Xcopy Games\TRAP-Editor\Assets bin\Release-windows-x86_64\Games\TRAP-Editor\Assets /I /H /E /C
        Xcopy Games\TRAP-Editor\Resources bin\Release-windows-x86_64\Games\TRAP-Editor\Resources /I /H /E /C
        Xcopy Licenses bin\Release-windows-x86_64\Licenses /I /H /E /C
        Xcopy Utility\QOIConv bin\Release-windows-x86_64\Utility\QOIConv /I /H /E /C
        Xcopy Redists bin\Release-windows-x86_64\Redists /I /H /E /C
        Get-ChildItem -Path "bin" -Filter "*.pdb" -Recurse | Remove-Item -Force
        Remove-Item bin\Release-windows-x86_64\Utility\QOIConv\QOIConv
    - name: Upload artifacts (TrappedGames)
      env:
        artifact_hostname: ${{secrets.ARTIFACT_HOST}}
      if: env.artifact_hostname != null
      uses: ./.github/composite/artifact-upload
      with:
        target-filename: Windows MSVC Release Executables
        server-hostname: ${{ secrets.ARTIFACT_HOST }}
        server-share: "artifacts"
        server-username: ${{ secrets.ARTIFACT_USERNAME }}
        server-password: ${{ secrets.ARTIFACT_PASSWORD }}
        folder-to-upload: >
          bin/Release-windows-x86_64/./Games
          bin/Release-windows-x86_64/./Utility
          bin/Release-windows-x86_64/./UnitTests
          bin/Release-windows-x86_64/./Licenses
          bin/Release-windows-x86_64/./Redists
    - name: Upload artifacts (GitHub)
      env:
        artifact_hostname: ${{secrets.ARTIFACT_HOST}}
      if: env.artifact_hostname == null
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: Windows MSVC Release Executables
        path: |
          bin/Release-windows-x86_64/Games
          bin/Release-windows-x86_64/Utility
          bin/Release-windows-x86_64/UnitTests
          bin/Release-windows-x86_64/Licenses
          bin/Release-windows-x86_64/Redists

  test-windows:
    name: Unit-Test Windows
    runs-on: [self-hosted, windows, "2025", X64, cpu]
    needs: [build-windows-msvc-2025]
    steps:
      - name: Cleanup workspace
        if: ${{ always() }}
        uses: gamestrap/gha-workspace-cleanup@a4ba9185d186048c239232b7164d5215aa544974 #v2.0.0
      - name: Download artifact (TrappedGames)
        env:
          artifact_hostname: ${{secrets.ARTIFACT_HOST}}
        if: env.artifact_hostname != null
        uses: gamestrap/gha-download-artifact@ed04b8e83a34e86c6bec2a999a4fce223b296560 #v1.0.5
        with:
          server-hostname: ${{ secrets.ARTIFACT_HOST }}
          server-share: "artifacts"
          server-username: ${{ secrets.ARTIFACT_USERNAME }}
          server-password: ${{ secrets.ARTIFACT_PASSWORD }}
          artifact-name: "Windows MSVC Release Executables"
      - name: Download artifact (GitHub)
        env:
          artifact_hostname: ${{secrets.ARTIFACT_HOST}}
        if: env.artifact_hostname == null
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          name: Windows MSVC Release Executables
      - name: Run Tests
        run: |
          cd UnitTests
          $env:TRACY_NO_INVARIANT_CHECK=1; .\UnitTests.exe; Remove-Item Env:\TRACY_NO_INVARIANT_CHECK
  test-linux:
    name: Unit-Test Linux
    runs-on: [self-hosted, Linux, X64, ubuntu, "26.04", cpu]
    needs: [build-linux-clang-22]
    steps:
      - name: Cleanup workspace
        if: ${{ always() }}
        uses: gamestrap/gha-workspace-cleanup@a4ba9185d186048c239232b7164d5215aa544974 #v2.0.0
      - name: Download artifact (TrappedGames)
        env:
          artifact_hostname: ${{secrets.ARTIFACT_HOST}}
        if: env.artifact_hostname != null
        uses: gamestrap/gha-download-artifact@ed04b8e83a34e86c6bec2a999a4fce223b296560 #v1.0.5
        with:
          server-hostname: ${{ secrets.ARTIFACT_HOST }}
          server-share: "artifacts"
          server-username: ${{ secrets.ARTIFACT_USERNAME }}
          server-password: ${{ secrets.ARTIFACT_PASSWORD }}
          artifact-name: "Linux Clang Release Executables"
      - name: Download artifact (GitHub)
        env:
          artifact_hostname: ${{secrets.ARTIFACT_HOST}}
        if: env.artifact_hostname == null
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          name: Linux Clang Release Executables
      - name: Run Tests
        run: |
          cd UnitTests
          chmod +x UnitTests
          TRACY_NO_INVARIANT_CHECK=1 ./UnitTests
