# Main Build CI. This compiles TRAP™ for Windows and Linux (Ubuntu)

name: Build-CI

# Controls when the workflow will run
on:
  # Run on all pull requests
  pull_request:
  # Run on master and dev branches
  push:
    branches: [ master, dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux-gcc-10:
    name: Build Linux GCC 10
    runs-on: ubuntu-22.04
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    # Check-out repository and submodules under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    # Update package list
    - name: Update package list
      run: sudo apt update
    # Install G++ & GCC 10
    - name: Install G++ & GCC 10 multilib
      run: sudo apt install -y g++-10-multilib gcc-10-multilib
    # Install X11 dependencies
    - name: Install X11 dependencies
      run: sudo apt install -y xorg-dev
    # Install Wayland dependencies
    - name: Install Wayland dependencies
      run: sudo apt install -y libwayland-dev libxkbcommon-dev wayland-protocols
    # Setup the Vulkan SDK
    - name: Prepare latest Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    # Make scripts and premake executable
    - name: Set Execute flags
      run: |
       chmod +x libs/premake5/linux/premake5
       chmod +x GeneratorScripts/GenerateProjectMake.sh
    - name: Generate Make files
      run: |
       cd GeneratorScripts/
       ./GenerateProjectMake.sh
       cd ..
    - name: Compile code using g++-10
      run: config=release make all -j2
    - name: Copy Assets
      run: |
        cp -r Games/Headless-Tests/Assets bin/Release-linux-x86_64/Games/Headless-Tests/
        cp -r Games/Sandbox/Assets bin/Release-linux-x86_64/Games/Sandbox/
        cp -r Games/Tests/Assets bin/Release-linux-x86_64/Games/Tests/
        cp -r Games/Tests3D/Assets bin/Release-linux-x86_64/Games/Tests3D/
        cp -r Games/TRAP-Editor/Assets bin/Release-linux-x86_64/Games/TRAP-Editor/
        cp -r Games/TRAP-Editor/Resources bin/Release-linux-x86_64/Games/TRAP-Editor/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Ubuntu 22.04 Release Executables
        path: |
          bin/Release-linux-x86_64/Games
          bin/Release-linux-x86_64/Utility
          Utility/QOIConv/QOIConv*
  build-windows-msvc-2022:
    name: Build Windows MSVC 2022
    runs-on: windows-2022
    steps:
    # Check-out repository and submodules under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    # Setup the Vulkan SDK
    - name: Prepare latest Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    # Setup msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    # Generate the Visual Studio 2022 Project files
    - name: Generate Visual Studio 2022 Project files
      run: cd GeneratorScripts && .\GenerateProjectVS2022.bat && cd ..
    - name: Compile code
      run: msbuild /m TRAP.sln /property:Configuration=Release
    - name: Copy Assets
      run: |
        Xcopy Games/Headless-Tests/Assets bin/Release-linux-x86_64/Games/Headless-Tests/ /E /H /C /I
        Xcopy Games/Sandbox/Assets bin/Release-linux-x86_64/Games/Sandbox/ /E /H /C /I
        Xcopy Games/Tests/Assets bin/Release-linux-x86_64/Games/Tests/ /E /H /C /I
        Xcopy Games/Tests3D/Assets bin/Release-linux-x86_64/Games/Tests3D/ /E /H /C /I
        Xcopy Games/TRAP-Editor/Assets bin/Release-linux-x86_64/Games/TRAP-Editor/ /E /H /C /I
        Xcopy Games/TRAP-Editor/Resources bin/Release-linux-x86_64/Games/TRAP-Editor/ /E /H /C /I
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSVC 2022 Release Executables
        path: |
          bin/Release-windows-x86_64/Games
          bin/Release-windows-x86_64/Utility
          Utility/QOIConv/QOIConv*
  build-windows-msvc-2019:
    name: Build Windows MSVC 2019
    runs-on: windows-2019
    steps:
    # Check-out repository and submodules under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    # Setup the Vulkan SDK
    - name: Prepare latest Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    # Setup msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    # Generate the Visual Studio 2019 Project files
    - name: Generate Visual Studio 2019 Project files
      run: cd GeneratorScripts && .\GenerateProjectVS2019.bat && cd ..
    - name: Compile code
      run: msbuild /m TRAP.sln /property:Configuration=Release
    - name: Copy Assets
      run: |
        Xcopy Games/Headless-Tests/Assets bin/Release-linux-x86_64/Games/Headless-Tests/ /E /H /C /I
        Xcopy Games/Sandbox/Assets bin/Release-linux-x86_64/Games/Sandbox/ /E /H /C /I
        Xcopy Games/Tests/Assets bin/Release-linux-x86_64/Games/Tests/ /E /H /C /I
        Xcopy Games/Tests3D/Assets bin/Release-linux-x86_64/Games/Tests3D/ /E /H /C /I
        Xcopy Games/TRAP-Editor/Assets bin/Release-linux-x86_64/Games/TRAP-Editor/ /E /H /C /I
        Xcopy Games/TRAP-Editor/Resources bin/Release-linux-x86_64/Games/TRAP-Editor/ /E /H /C /I
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSVC 2019 Release Executables
        path: |
          bin/Release-windows-x86_64/Games
          bin/Release-windows-x86_64/Utility
          Utility/QOIConv/QOIConv*
