# Documentation Build. This generates the Documentation website for TRAP™

name: Build-Docs

# Controls when the workflow will run
on:
  # Run on when a new tag is added
  push:
    tags:
      - '**'
  # Allow to run this action manually
  workflow_dispatch:

jobs:
  build-docs-linux:
    name: Build Docs Linux
    runs-on: [self-hosted, Linux, X64, ubuntu, "24.10", cpu]
    steps:
    - name: Cleanup workspace
      if: ${{ always() }}
      uses: gamestrap/gha-workspace-cleanup@v1.2.5
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Check-out submodules (with retries)
      run: |
        git submodule sync && \
        (git -c protocol.version=2 submodule update --init --force --depth=1 || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) || \
         (sleep 10 && git -c protocol.version=2 submodule update --init --force --depth=1) \
        )
    - name: Install dependencies
      run: sudo apt install -y doxygen python3-venv graphviz
    - name: Make python3 available as python
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - name: Make pip3 available as pip
      run: sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
    - name: Set Execute flags
      run: |
        chmod +x libs/premake5/linux/premake5
        chmod +x GeneratorScripts/GenerateDocumentation.sh
    - name: Generate Documentation
      run: |
        cd GeneratorScripts/
        ./GenerateDocumentation.sh
        cd ..
    - name: Check-out TRAP-Docs repository
      uses: actions/checkout@v4
      with:
        repository: 'GamesTrap/TRAP-Docs'
        path: 'TRAP-Docs'
    - uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_committer_name: TRAP CI/CD
        workdir: 'TRAP-Docs'
    - uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: "TRAP-Docs"
    - name: Retrieve new docs version
      id: get-docs-version
      run: echo "DOCS_VERSION=$(grep -oP -m 1 '\d+w\d+[a-zA-Z]+\d+' .modules/generatedocs/pages/changelog.md)" >> "$GITHUB_OUTPUT"
    - name: Move documentation to TRAP-Docs
      run: |
        rm -rf TRAP-Docs/docs/
        mv docs/ TRAP-Docs/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        path: 'TRAP-Docs'
        branch: docs-update/${{steps.get-docs-version.outputs.DOCS_VERSION}}
        delete-branch: true
        add-paths: docs/**
        commit-message: "Update Documentation to ${{steps.get-docs-version.outputs.DOCS_VERSION}} [skip ci]"
        title: "Update Documentation to ${{steps.get-docs-version.outputs.DOCS_VERSION}} [skip ci]"
        labels: "CI/CD, Documentation, Update"
        assignees: "GamesTrap"
        milestone: 1
        token: ${{steps.generate-token.outputs.token}}
        author: "TRAP CI/CD <no-reply@trappedgames.de>"
        committer: "TRAP CI/CD <no-reply@trappedgames.de>"
