# Documentation Build. This generates the Documentation website for TRAP™

name: Build-Docs

# Controls when the workflow will run
on:
  # Run on main and master branch
  push:
    branches: [ main, master ]
  # Allow to run this action manually
  workflow_dispatch:

jobs:
  build-docs-linux:
    name: Build Docs Linux
    runs-on: [self-hosted, Linux, X64, ubuntu, 23.04, cpu]
    steps:
    - name: Cleanup workspace
      if: ${{ always() }}
      uses: gamestrap/gha-workspace-cleanup@v1.2.3
    - name: Check-out repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install dependencies
      run: sudo apt install -y doxygen pip python3-sphinx
    - name: Make python3 available as python
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - name: Make pip3 available as pip
      run: sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
    - name: Set Execute flags
      run: |
        chmod +x libs/premake5/linux/premake5
        chmod +x GeneratorScripts/GenerateDocumentation.sh
    - name: Generate Documentation
      run: |
        cd GeneratorScripts/
        ./GenerateDocumentation.sh
        cd ..
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<noreply@github.com>"
    - name: Commit & push changes to master
      run: |
        git add docs/**
        git commit -m "[CI] Updated docs"
        git push
